[package]
name = "hi_sparse_bitset"
version = "0.1.0"
edition = "2021"

[features]
default = ["simd"]
simd = ["dep:wide"]

[dependencies]
num-traits = "0.2"
wide = { version = "0.7.13", optional = true }

[dev-dependencies]
rand = "0.8"
itertools = "0.11"
criterion = "0.5.1"
cfg-if = "1"
# for benchmarks
hibitset = "0.6.4"
roaring = "0.10.2"

#[profile.bench]
#lto = "thin"

[[bench]]
name = "intersection_bench"
path = "benches/intersection.rs"
harness = false

[[bench]]
name = "union_bench"
path = "benches/union.rs"
harness = false
