[package]
name = "hi_sparse_bitset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["simd"]
simd = ["dep:wide"]

[dependencies]
num-traits = "0.2"
#replace_with = "0.1"
wide = { version = "0.7.13", optional = true }

[dev-dependencies]
rand = "0.8"
itertools = "0.11"