name: CI

on:
  workflow_dispatch:  
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --no-default-features
      - run: RUSTFLAGS="--deny warnings" cargo build
      - run: RUSTFLAGS="--deny warnings" cargo build --all-features

  tests:
    uses: ./.github/workflows/tests.yml
    with:
      rustflags: '--deny warnings'

  benchmarks:
    name: benchmarks build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: RUSTFLAGS="--deny warnings" cargo build --benches --all-features

  doc:
    name: doc build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: RUSTFLAGS="--deny warnings" cargo doc --lib --all-features
        
  docrs:
    name: docrs build
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@nightly
      - uses: actions/checkout@v4
      - run: 
          RUSTFLAGS="--deny warnings" 
          RUSTDOCFLAGS="--cfg docsrs" 
          cargo +nightly doc --lib --all-features