name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: RUSTFLAGS="--deny warnings" cargo build

  tests:
    name: careful tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cache_type_flag: [
          hisparsebitset_test_NoCache,
          hisparsebitset_test_FixedCache,
          hisparsebitset_test_DynamicCache
        ]
        config_type_flag: [
          hisparsebitset_test_64,
          hisparsebitset_test_128
        ]
    steps:
    #- uses: dtolnay/rust-toolchain@nightly
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-careful
    - uses: actions/checkout@v4
    - run: RUSTFLAGS="
             --deny warnings 
             --cfg ${{ matrix.cache_type_flag }} ${{ matrix.config_type_flag }}
           " # cargo +nightly careful test --all-features
             cargo test --all-features

  miri:
    name: miri tests
    runs-on: ubuntu-latest
    steps:
    - uses: dtolnay/rust-toolchain@nightly
      with:
        toolchain: nightly
        components: miri
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-nextest
    - uses: actions/checkout@v4
    - run: RUSTFLAGS="--deny warnings" cargo +nightly miri nextest run -j6 --all-features


#  build-all-features:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    #- uses: ATiltedTree/setup-rust@v1
#    #  with:
#    #    rust-version: stable
#    - name: Build with all features
#      run: RUSTFLAGS="--deny warnings" cargo build --all-features
#
#  tests:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    #- uses: ATiltedTree/setup-rust@v1
#    #  with:
#    #    rust-version: stable
#    - name: Run tests
#      run: RUSTFLAGS="--deny warnings" cargo test --all-features
#
#  miri:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    #- uses: ATiltedTree/setup-rust@v1
#    #  with:
#    #    rust-version: stable
#    - uses: actions-rs/toolchain@v1
#      with:
#          toolchain: nightly
#          components: miri
#    - name: Miri tests
#      run: RUSTFLAGS="--deny warnings" cargo +nightly miri test
#
#  benches:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    #- uses: ATiltedTree/setup-rust@v1
#    #  with:
#    #    rust-version: stable
#    - name: Build benches
#      run: RUSTFLAGS="--deny warnings" cargo build --benches
#
#  doc:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    #- uses: ATiltedTree/setup-rust@v1
#    #  with:
#    #    rust-version: stable
#    - name: Build doc
#      run: RUSTDOCFLAGS="--deny warnings" cargo doc --lib